name: Build

on:
  workflow_call:
    inputs:
      os:
        type: string
        required: true
      python-version:
        type: string
        required: true
    secrets:
      kiss-cf-token:
        required: true

jobs:
  build:
    runs-on: ${{ inputs.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Checkout kiss_cf
      uses: actions/checkout@v3
      with:
        repository: alexander-rd/kiss_cf
        path: kiss_cf
        # TODO: remove token once repo becomes bublic
        token: ${{ secrets.kiss-cf-token }}

    - name: Setup
      uses: ./kiss_cf/.github/actions/setup
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install kiss_cf (if called from using project)
      run: pip install -e./kiss_cf
      if: inputs.is-self == 'no'

    - name: Orientation (ls)
      run: ls -la
      if: runner.os == 'Linux'

    # BUILD (linux)
    - name: Build (linux)
      run: ./build_linux.sh
      if: runner.os == 'Linux'
    - name: Upload (linux)
      uses: actions/upload-artifact@v3
      with:
        name: build_linux
        path: dist/SolawiDollingerTool
      if: runner.os == 'Linux'

    # BUILD (windows)
    - name: Build (windows)
      run: ./build_windows.bat
      if: runner.os == 'Windows'
    - name: Upload (windows)
      uses: actions/upload-artifact@v3
      with:
        name: build_windows
        path: dist/SolawiDollingerTool.exe
      if: runner.os == 'Windows'