name: Build

on:
  workflow_call:
    inputs:
      os:
        type: string
        required: true
      python-version:
        type: string
        required: true
    secrets:
      kiss-cf-token:
        required: true

jobs:
  build:
    runs-on: ${{ inputs.os }}

    steps:

    # BUILD (linux)
    - name: Build (linux)
      run: ./build_linux.sh
      if: runner.os == 'Linux'
    - name: Upload (linux)
      uses: actions/upload-artifact@v4
      with:
        name: build_linux
        path: dist/*
        retention-days: 2
      if: runner.os == 'Linux'

    # BUILD (windows)
    - name: Build (windows)
      run: ./build_windows.bat
      if: runner.os == 'Windows'
    - name: Upload (windows)
      uses: actions/upload-artifact@v4
      with:
        name: build_windows
        path: dist/*
        retention-days: 2
      if: runner.os == 'Windows'