# Copyright 2026 the contributors of APPXF (github.com/alexander-rd/appxf)
# SPDX-License-Identifier: 0BSD

name: CI
on:
  - pull_request
# Performing sanity checks on pull requests like license headers, flake8 and
# unit tests without credentials.

# TODO: this workflow is work in progress. Unit tests need splitting and the
# ones without credentials to be moved here. Also, flake8 is not yet active.

jobs:
  license_headers:
    name: Verify license headers
    runs-on: ubuntu-slim
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Verify file headers
        run: scripts/file_checkers.sh
